src/main/java/com/naturalprogrammer/spring/sample/dto/ForgotPasswordForm.java
package com.naturalprogrammer.spring.sample.dto;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import com.naturalprogrammer.spring.sample.entity.User;

/**
 * @author glaubernespoli
 * @created dez 18, 2015
 */
public class ForgotPasswordForm {

	@NotBlank
	@Size(min = 1, max = User.EMAIL_MAX, message = "{signup.email.size}")
	@Email(message = "{signup.email.invalid}")
	private String email;

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}

src/main/java/com/naturalprogrammer/spring/sample/dto/ResetPasswordForm.java
package com.naturalprogrammer.spring.sample.dto;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

import com.naturalprogrammer.spring.sample.entity.User;

/**
 * @author glaubernespoli
 * @created dez 18, 2015
 */
public class ResetPasswordForm {

	@NotBlank
	@Size(min = 6, max = User.PASSWORD_MAX, message = "{signup.password.size}")
	private String password;

	@NotBlank
	@Size(min = 6, max = User.PASSWORD_MAX, message = "{signup.password.size}")
	private String retypePassword;

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRetypePassword() {
		return retypePassword;
	}

	public void setRetypePassword(String retypePassword) {
		this.retypePassword = retypePassword;
	}
}

src/main/java/com/naturalprogrammer/spring/sample/dto/SignupForm.java
package com.naturalprogrammer.spring.sample.dto;

import javax.validation.constraints.Size;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import com.naturalprogrammer.spring.sample.entity.User;

/**
 * @author glaubernespoli
 * @created dez 14, 2015
 */
public class SignupForm {

	@NotBlank(message = "{signup.email.blank}")
	@Size(min = 1, max = 250, message = "{signup.email.size}")
	@Email(message = "{signup.email.invalid}")
//	@Pattern(regexp = "[A-Za-z0-9._%-+]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}")
	private String email;

	@NotBlank(message = "{signup.name.blank}")
	@Size(min = 1, max = 100, message = "{signup.name.size}")
	private String name;

	@NotBlank(message = "{signup.password.blank}")
	@Size(min = 6, max = User.PASSWORD_MAX, message = "{signup.password.size}")
	private String password;

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}
}

src/main/java/com/naturalprogrammer/spring/sample/dto/UserEditForm.java
package com.naturalprogrammer.spring.sample.dto;

import java.util.Set;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.naturalprogrammer.spring.sample.entity.User;

/**
 * @author glaubernespoli
 * @created jan 07, 2016
 */
public class UserEditForm {

	@NotNull
	@Size(min = 1, max = User.NAME_MAX, message = "{nameSizeError}")
	private String name;

	private Set<User.Role> roles;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<User.Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<User.Role> roles) {
		this.roles = roles;
	}
}

src/main/java/com/naturalprogrammer/spring/sample/entity/User.java
package com.naturalprogrammer.spring.sample.entity;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

import com.naturalprogrammer.spring.sample.util.MyUtil;

/**
 * @author glaubernespoli
 * @created dez 15, 2015
 */
@Entity
@Table(name = "usr", indexes = {@Index(name = "IDX_EMAIL", columnList = "email", unique = true)})
public class User {

	public static final int EMAIL_MAX = 250;

	public static final int NAME_MAX = 100;

	//public static final String EMAIL_PATTERN = "[A-Za-z0-9._%-+]+@[A-Za-z0-9.-]+\\\\.[A-Za-z]{2,4}";

	public static final int RANDOM_CODE_LENGTH = 16;

	public static final int PASSWORD_MAX = 30;

	public enum Role {
		UNVERIFIED, BLOCKED, ADMIN
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(nullable = false, length = EMAIL_MAX)
	private String email;

	@Column(nullable = false, length = NAME_MAX)
	private String name;

	@Column(nullable = false)
	private String password;

	@Column(length = RANDOM_CODE_LENGTH)
	private String verificationCode;

	@Column(length = RANDOM_CODE_LENGTH, unique = true)
	private String forgotPasswordCode;

	@Column(name = "role")
	@CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
	@Enumerated(EnumType.STRING)
	@ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
	private Set<Role> roles = new HashSet<>();

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getVerificationCode() {
		return verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	public String getForgotPasswordCode() {
		return forgotPasswordCode;
	}

	public void setForgotPasswordCode(String forgotPasswordCode) {
		this.forgotPasswordCode = forgotPasswordCode;
	}

	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public boolean isAdmin() {
		return roles.contains(Role.ADMIN);
	}

	public boolean isEditable() {
		User loggedIn = MyUtil.getSessionUser();
		return loggedIn != null && (loggedIn.isAdmin() || Objects.equals(loggedIn.getId(), id));
	}
}

src/main/java/com/naturalprogrammer/spring/sample/controller/HomeController.java
package com.naturalprogrammer.spring.sample.controller;

import javax.validation.Valid;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.springframework.web.servlet.view.UrlBasedViewResolver;

import com.naturalprogrammer.spring.sample.dto.ForgotPasswordForm;
import com.naturalprogrammer.spring.sample.dto.ResetPasswordForm;
import com.naturalprogrammer.spring.sample.dto.SignupForm;
import com.naturalprogrammer.spring.sample.service.UserService;
import com.naturalprogrammer.spring.sample.util.MyUtil;
import com.naturalprogrammer.spring.sample.validator.ForgotPasswordFormValidator;
import com.naturalprogrammer.spring.sample.validator.ResetPasswordFormValidator;
import com.naturalprogrammer.spring.sample.validator.SignupFormValidator;

/**
 * @author glaubernespoli
 * @created dez 09, 2015
 */
@Controller
public class HomeController {

	private static final Log log = LogFactory.getLog(HomeController.class);

	private UserService userService;

	private SignupFormValidator signupFormValidator;

	private ForgotPasswordFormValidator forgotPasswordFormValidator;

	private ResetPasswordFormValidator resetPasswordFormValidator;

	@Autowired
	public HomeController(UserService userService, SignupFormValidator signupFormValidator, ForgotPasswordFormValidator forgotPasswordFormValidator, ResetPasswordFormValidator resetPasswordFormValidator) {
		this.userService = userService;
		this.signupFormValidator = signupFormValidator;
		this.forgotPasswordFormValidator = forgotPasswordFormValidator;
		this.resetPasswordFormValidator = resetPasswordFormValidator;
	}

	@InitBinder("signUp")
	protected void initSignUpBinder(WebDataBinder webDataBinder) {
		webDataBinder.setValidator(signupFormValidator);
	}

	@InitBinder("forgotPasswordForm")
	protected void initForgotPasswordBinder(WebDataBinder webDataBinder) {
		webDataBinder.setValidator(forgotPasswordFormValidator);
	}

	@InitBinder("resetPasswordForm")
	protected void initResetPasswordBinder(WebDataBinder webDataBinder) {
		webDataBinder.setValidator(resetPasswordFormValidator);
	}

	@RequestMapping(value = "/signup", method = RequestMethod.GET)
	public String signup(Model model) {
		model.addAttribute("signUp", new SignupForm());
		return "signup";
	}

	@RequestMapping(value = "/signup", method = RequestMethod.POST)
	public String signup(@ModelAttribute("signUp") @Valid SignupForm signupForm, BindingResult result, RedirectAttributes redirectAttributes) {
		if(result.hasErrors()) {
			return "signup";
		}

		userService.signup(signupForm);
		log.info(signupForm.toString());

		MyUtil.flash(redirectAttributes, "success", "signup.success");
		return UrlBasedViewResolver.REDIRECT_URL_PREFIX + "/";
	}

	@RequestMapping(value = "/forgot-password", method = RequestMethod.GET)
	public String forgotPassword(Model model) {
		model.addAttribute("forgotPasswordForm", new ForgotPasswordForm());
		return "forgot-password";
	}

	@RequestMapping(value = "/forgot-password", method = RequestMethod.POST)
	public String forgotPassword(@ModelAttribute("forgotPasswordForm") @Valid ForgotPasswordForm forgotPasswordForm, BindingResult result, RedirectAttributes redirectAttributes) {
		if(result.hasErrors()) {
			return "forgot-password";
		}

		userService.forgotPassword(forgotPasswordForm);
//		log.info(signupForm.toString());

		MyUtil.flash(redirectAttributes, "info", "checkMailResetPassword");
		return UrlBasedViewResolver.REDIRECT_URL_PREFIX + "/";
	}

	@RequestMapping(value = "/reset-password/{forgotPasswordCode}", method = RequestMethod.GET)
	public String resetPassword(@PathVariable("forgotPasswordCode") String forgotPasswordCode, Model model) {
		model.addAttribute("resetPasswordForm", new ResetPasswordForm());
				return "reset-password";
	}

	@RequestMapping(value = "/reset-password/{forgotPasswordCode}", method = RequestMethod.POST)
	public String resetPassword(@PathVariable("forgotPasswordCode") String forgotPasswordCode, @ModelAttribute("resetPasswordForm") @Valid ResetPasswordForm resetPasswordForm,
	                            BindingResult result, RedirectAttributes redirectAttributes) {
		if(result.hasErrors()) {
			return "reset-password";
		}

		userService.resetPassword(forgotPasswordCode, resetPasswordForm, result);

		if(result.hasErrors()) {
			return "reset-password";
		}

		MyUtil.flash(redirectAttributes, "info", "passwordChanged");
		return UrlBasedViewResolver.REDIRECT_URL_PREFIX + "/login";
	}
}

src/main/webapp/WEB-INF/jsp/error.jsp
<%@include file="includes/header.jsp"%>
	<div class="alert alert-danger">
		<p>There was an enexpected error (type=${error}, status=${status}): <i>${message}</i></p>
		<p>Click <a href="/">here</a> to go to home page.</p>
	</div>
<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/forgot-password.jsp
<%@include file="includes/header.jsp"%>

<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Forgot password?</h3>
	</div>

	<div class="panel-body">
		<form:form modelAttribute="forgotPasswordForm" role="form">

			<form:errors />

			<div class="form-group">
				<form:label path="email">Email Address</form:label>
				<form:input path="email" type="email" class="form-control" placeholder="Enter email" />
				<form:errors cssClass="error" path="email" />
				<p class="help-block">Please enter your email id.</p>
			</div>

			<button type="submit" class="btn btn-default">Reset password</button>
		</form:form>
	</div>
</div>

<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/home.jsp
<%@include file="includes/header.jsp"%>
	<spring:message code="hello" />
<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@include file="includes/header.jsp"%>

<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Please sign in</h3>
	</div>

	<div class="panel-body">
		<c:if test="${null ne param.error}">
			<div class="alert alert-danger">
				Invalid username or password.
			</div>
		</c:if>

		<c:if test="${null ne param.logout}">
			<div class="alert alert-danger">
				You have been logged out.
			</div>
		</c:if>

		<form:form role="form" method="post">
			<div class="form-group">
				<label for="username">Email address</label>
				<input id="username" name="username" type="email" class="form-control">
				<p class="help-block">Enter your email address.</p>
			</div>

			<div class="form-group">
				<label for="password">Password</label>
				<input id="password" name="password" type="password" class="form-control">
				<form:errors cssClass="error" path="password" />
			</div>

			<div class="form-group">
				<div class="checkbox">
					<label>
						<input type="checkbox" name="remember-me"> Remember me
					</label>
				</div>
			</div>

			<button type="submit" class="btn btn-primary">Sign In</button>
			<a href="/forgot-password" class="btn btn-default">Forgot Password</a>
		</form:form>
	</div>
</div>

<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/profile.jsp
<%@include file="includes/header.jsp"%>
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Profile</h3>
	</div>

	<div class="panel-body">
		<dl class="dl-horizontal">
			<dt>Name</dt>
			<dd><c:out value="${user.name}" /></dd>
			<dt>Email</dt>
			<dd><c:out value="${user.email}" /></dd>
			<dt>Roles</dt>
			<dd><c:out value="${user.roles}" /></dd>
		</dl>
	</div>

	<c:if test="${user.editable}">
		<div class="panel-footer">
			<a href="/users/${user.id}/edit" class="btn btn-link">Edit</a>
			<a href="/users/${user.id}/change-password" class="btn btn-link">Change password</a>
			<a href="/users/${user.id}/change-email" class="btn btn-link">Change email</a>
		</div>
	</c:if>
</div>
<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/reset-password.jsp
<%@include file="includes/header.jsp"%>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Reset password</h3>
	</div>

	<div class="panel-body">
		<form:form modelAttribute="resetPasswordForm" role="form">

			<form:errors />

			<div class="form-group">
				<form:label path="password">Type new password</form:label>
				<form:input path="password" type="password" class="form-control" placeholder="Password" />
				<form:errors cssClass="error" path="password" />
			</div>

			<div class="form-group">
				<form:label path="retypePassword">Retype new password</form:label>
				<form:input path="retypePassword" type="password" class="form-control" placeholder="Retype password" />
				<form:errors cssClass="error" path="retypePassword" />
			</div>

			<button type="submit" class="btn btn-default">Submit</button>
		</form:form>
	</div>
</div>

<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/signup.jsp
<%@include file="includes/header.jsp"%>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Please signup</h3>
	</div>

	<div class="panel-body">
		<form:form modelAttribute="signUp" role="form">

			<form:errors />

			<div class="form-group">
				<form:label path="email">Email Address</form:label>
				<form:input path="email" type="email" class="form-control" placeholder="Enter email" />
				<form:errors cssClass="error" path="email" />
				<p class="help-block">Enter a unique email address. It will also be your login id.</p>
			</div>

			<div class="form-group">
				<form:label path="name">Name</form:label>
				<form:input path="name" class="form-control" placeholder="Enter name" />
				<form:errors cssClass="error" path="name" />
				<p class="help-block">Enter your display name.</p>
			</div>

			<div class="form-group">
				<form:label path="password">Password</form:label>
				<form:password path="password" class="form-control" placeholder="Enter password" />
				<form:errors cssClass="error" path="password" />
			</div>

			<button type="submit" class="btn btn-default">Submit</button>
		</form:form>
	</div>
</div>

<%@include file="includes/footer.jsp"%>

src/main/webapp/WEB-INF/jsp/user-edit.jsp
<%@include file="includes/header.jsp"%>
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Profile</h3>
	</div>

	<div class="panel-body">
	<form:form modelAttribute="userEditForm" class="form-horizontal" role="form">
		<div class="form-group">
			<form:label path="name" class="col-lg-2 control-label">Name</form:label>
			<div class="col-lg-10">
				<form:input path="name" class="form-control" placeholder="Name" />
				<form:errors cssClass="error" path="name" />
				<p class="help-block">Enter your display name.</p>
			</div>
		</div>

		<sec:authorize access="hasRole('ROLE_ADMIN')">
			<div class="form-group">
				<form:label path="roles" class="col-lg-2 control-label">Roles</form:label>
				<div class="col-lg-10">
					<form:input path="roles" class="form-control" placeholder="Roles" />
					<form:errors cssClass="error" path="roles" />
					<p class="help-block">Enter the roles of the user, separated by commas.</p>
				</div>
			</div>
		</sec:authorize>

		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-primary">Save</button>
			</div>
		</div>
	</form:form>
</div>
<%@include file="includes/footer.jsp"%>